ninety-nine-cats/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "cats#index"
  resources :cats, except: [:destroy] 

end

ninety-nine-cats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

ninety-nine-cats/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint           not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Cat < ApplicationRecord
    CAT_COLORS = ["white", "brown", "black", "orange", "grey"]
    validates :birth_date, :color, :name, :sex, presence: true 
    validates :color, inclusion: {in: CAT_COLORS, message: "%{value} is not a valid color" }
    validates :sex, inclusion: {in: ["M", "F"], message: "%{value} is not a valid sex" }
    validate :birth_date_cannot_be_future

    def birth_date_cannot_be_future
        if birth_date > Date.today
            errors.add(:birth_date, "birth date cannot be in future")
        end
    end

    def age
        Date.today.year - birth_date.year
    end
end

ninety-nine-cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

ninety-nine-cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController

    def create
        @cat = Cat.new(cat_params)
        if @cat.save
            render json: @cat
        else
            render json: @cat.errors.full_messages
        end
    end

    def index
        @cats = Cat.all
        render :index
    end

    def show
        @cat = Cat.find(params[:id])
        render :show
    end

    def update
        #find the cat
        #modify the cat
        #render the cat
        @cat = Cat.find(params[:id])
        @cat.update(cat_params)
        if @cat.save
            render json: @cat
        else
            render json: @cat.errors.full_messages
        end 
    end

    def new
        @cat = Cat.new
        render :new
    end

    def edit
        @cat = Cat.find(params[:id])
        render :edit
    end

    private
    def cat_params
        params.permit(:birth_date, :color, :name, :sex, :description)
    end
end

ninety-nine-cats/app/helpers/application_helper.rb
module ApplicationHelper
end

ninety-nine-cats/app/helpers/cats_helper.rb
module CatsHelper
end

ninety-nine-cats/app/views/cats/index.html.erb
<% @cats.each do |cat|%>
<ul>
    <li>
    <%= cat.name %>
    </li>
    <li>
    <a href= "<%= cat_url(cat) %>" > Link </a> 
    
    </li>
</ul>
    <%end%>

ninety-nine-cats/app/views/cats/new.html.erb
<h1>Add Cat</h1>
<form action = "<%=cats_url%>" method = "POST" >
<label for = "name"> Name </label>
<input id = "name" name = "cat[name]"> 
<label for = "color"> Color </label>
<input id = "color" name = "cat[color]">
<input type = "submit" value = "Add Cat">


</form>

ninety-nine-cats/app/views/cats/show.html.erb
<table>
    <thead>
        <tr>
            <th colspan="2"><%= @cat.name.capitalize %></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td> Birth Date </td>
            <td> <%=@cat.birth_date%> </td>
        </tr>
        <tr>
            <td> Color </td>
            <td> <%=@cat.color%> </td>
        </tr>
        <tr>
            <td> Sex </td>
            <td> <%=@cat.sex%> </td>
        </tr>
    </tbody>
</table>

ninety-nine-cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetyNineCats</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>